### ISSUE TITLE
Clarification on correct way to create instance.

### ISSUE THREAD

**Issue by xavier-taylor** [cvburgess/SQLDataSource#67]
Hi there. Thanks for the great library :)

In the docs, you show this example:
`// index.js

const MyDatabase = require("./MyDatabase");

const knexConfig = {
  client: "pg",
  connection: {
    /* CONNECTION INFO */
  }
};

// you can also pass a knex instance instead of a configuration object
const db = new MyDatabase(knexConfig);

const server = new ApolloServer({
  typeDefs,
  resolvers,
  cache,
  context,
  dataSources: () => ({ db })
});`

However, in the apollo docs for [data sources,](https://www.apollographql.com/docs/apollo-server/data/data-sources/#adding-data-sources-to-apollo-server), they say: 

>     As shown, the dataSources option is a function. This function returns an object containing instances of your DataSource subclasses (in this case, MoviesAPI and PersonalizationAPI).

>     Apollo Server calls this function for every incoming operation. It automatically assigns the returned object to the dataSources field of the context object that's passed between your server's resolvers.

>     Also as shown, the function should create a new instance of each data source for each operation. If multiple operations share a single data source instance, you might accidentally combine results from multiple operations.
    
   Do I understand correctly from your docs that in the case of your library, we should divert from the standard apollo practice, and instead create an instance and just pass it into dataSources? I suppose this is necessary for your caching approach?
   
  Do I understand correctly that if I instantiating the data source the way apollo recommends, I would not be able to use your .cache() functionality across separate queries? 
  
  Thanks again for the library and for any advice :)

**Comment by xavier-taylor** [comment]
While I am here, could I ask - without batching (which I understand I need to use Dataloader in addition to your library to achieve), what does SQLDataSource do - just provide for caching? Is there anything else it does?

(I initially added this library to my project thinking that it solved the N+1 problem by batching, but I have seen from discussions on other issues that batching support was removed from the library in the past).

**Comment by cvburgess** [comment]
You're welcome to look through the code for the last version which did attempt to batch.
Because of how knex works, it required me to execute some queries as raw SQL and do some not-so-great things that were brittle. I've found that this simple class-based utility that aligns with Apollo Datasources and integrates with your global apollo-defined cache, be it memory or redis has been very performant and done well in massive production environments.

If you'd like to take a stab at re-implementing batching, please open a PR!

I no longer work at a company actively using this library, my current team uses Hasura for our GraphQL APIs so I'm a little slower than I used to be on making updates here as I know many folks depend on this lib in production environments and its pretty battle tested.

**Comment by xavier-taylor** [comment]
No dramas mate. My use case is actually small and simple enough that I don't think I need the caching functionality after all - for now I have just implemented a simple use of Dataloader for batching. If my little app ever becomes a runaway success and I need a proper Apollo Datasource, I might return one day with a PR for you :)
