### ISSUE TITLE
Sequelize support?

### ISSUE THREAD

**Issue by tab00** [cvburgess/SQLDataSource#8]
This package looks like just what I need to connect Apollo with SQL database using Datasources, but I see that Knex is a hard dependency.

Was there a reason for choosing to use Knex over Sequelize?

Would it be possible to either to remove the hard dependency so that it can work with Sequelize, or add support for Sequelize using an initialization parameter?

**Comment by cvburgess** [comment]
If you want to open a PR for Sequelize I'd be happy to review it!

I personally use Knex, so that is what I built this lib around.

Knex is also a query builder, not an ORM so the support for this would probably require API changes.

The ORM  version of Knex is called Bookshelf which is much closer to Sequelize in terms of functionality. ( I personally dislike ORMs but have no objection to supporting them )

**Comment by cvburgess** [comment]
i dont see anyone stepping up for this so i will close until further notice
